local lush = require("lush")
local hsl = lush.hsl
local neonwave = require("neonwave")
local P = neonwave.get_palette()
local tr = neonwave.config.transparent_background
local canvas = tr and "NONE" or hsl(P.bg)
local chrome = tr and "NONE" or hsl(P.statusline)

---@diagnostic disable: undefined-global
return lush(function(injected)
  local sym = injected.sym

  return {
    Normal { bg = canvas, fg = hsl(P.fg) },
    NormalNC { bg = canvas, fg = hsl(P.fg_dim) },
    NormalFloat { bg = hsl(P.surface), fg = hsl(P.fg) },
    FloatBorder { fg = hsl(P.border), bg = hsl(P.surface) },
    FloatTitle { fg = hsl(P.float_title), bg = hsl(P.surface), gui = "bold" },

    Cursor { bg = hsl(P.pink), fg = hsl(P.cursor_fg) },
    lCursor { Cursor },
    CursorIM { Cursor },
    CursorLine { bg = hsl(P.cursor_line) },
    CursorColumn { bg = hsl(P.cursor_line) },
    ColorColumn { bg = hsl(P.surface_elevated) },
    LineNr { fg = hsl(P.line_nr), bg = canvas },
    LineNrAbove { LineNr },
    LineNrBelow { LineNr },
    CursorLineNr { fg = hsl(P.line_nr_cursor), gui = "bold" },
    SignColumn { bg = canvas, fg = hsl(P.line_nr) },
    FoldColumn { fg = hsl(P.comment), bg = canvas },
    Folded { fg = hsl(P.comment), bg = hsl(P.surface) },

    StatusLine { bg = chrome, fg = hsl(P.fg) },
    StatusLineNC { bg = chrome, fg = hsl(P.fg_dim) },
    TabLine { bg = chrome, fg = hsl(P.fg_dim) },
    TabLineFill { bg = chrome },
    TabLineSel { bg = hsl(P.tabline_sel), fg = hsl(P.pink), gui = "bold" },
    WinBar { bg = canvas, fg = hsl(P.fg_dim) },
    WinBarNC { bg = canvas, fg = hsl(P.comment) },

    VertSplit { fg = hsl(P.border), bg = canvas },
    Winseparator { VertSplit },

    Pmenu { bg = hsl(P.pmenu), fg = hsl(P.fg) },
    PmenuSel { bg = hsl(P.pmenu_sel), fg = hsl(P.fg) },
    PmenuSbar { bg = hsl(P.surface) },
    PmenuThumb { bg = hsl(P.pmenu_thumb) },
    WildMenu { bg = hsl(P.wildmenu), fg = hsl(P.fg) },

    Visual { bg = hsl(P.visual) },
    VisualNOS { Visual },
    Search { bg = hsl(P.search), fg = hsl(P.fg) },
    CurSearch { bg = hsl(P.inc_search), fg = hsl(P.on_search), gui = "bold" },
    IncSearch { CurSearch },
    Substitute { Search },

    Directory { fg = hsl(P.cyan) },
    Title { fg = hsl(P.title), gui = "bold" },
    Question { fg = hsl(P.cyan) },
    MoreMsg { fg = hsl(P.cyan) },
    ModeMsg { fg = hsl(P.pink) },
    MsgArea { Normal },
    MsgSeparator { fg = hsl(P.border) },

    ErrorMsg { fg = hsl(P.error), gui = "bold" },
    WarningMsg { fg = hsl(P.warn), gui = "bold" },

    MatchParen {
      bg = hsl(P.match_paren_bg),
      fg = hsl(P.pink_glow),
      sp = hsl(P.match_paren_sp),
      gui = "bold,undercurl",
    },

    NonText { fg = hsl(P.eob) },
    EndOfBuffer { NonText },
    Whitespace { fg = hsl(P.whitespace) },
    SpecialKey { fg = hsl(P.special) },

    SpellBad { sp = hsl(P.error), gui = "undercurl" },
    SpellCap { sp = hsl(P.warn), gui = "undercurl" },
    SpellLocal { sp = hsl(P.info), gui = "undercurl" },
    SpellRare { sp = hsl(P.hint), gui = "undercurl" },

    DiffAdd { bg = hsl(P.added) },
    DiffChange { bg = hsl(P.changed) },
    DiffDelete { bg = hsl(P.deleted) },
    DiffText { bg = hsl(P.surface_elevated), fg = hsl(P.cyan_glow) },

    QuickFixLine { bg = hsl(P.cursor_line) },

    Comment { fg = hsl(P.comment), gui = "italic" },
    Constant { fg = hsl(P.purple) },
    String { fg = hsl(P.string) },
    Character { String },
    Number { fg = hsl(P.number) },
    Boolean { fg = hsl(P.boolean) },
    Float { Number },

    Identifier { fg = hsl(P.fg) },
    Function { fg = hsl(P.cyan), gui = "bold" },

    Statement { fg = hsl(P.pink) },
    Conditional { Statement },
    Repeat { Statement },
    Label { fg = hsl(P.magenta) },
    Operator { fg = hsl(P.operator) },
    Keyword { fg = hsl(P.pink), gui = "bold" },
    Exception { Keyword },

    PreProc { fg = hsl(P.magenta) },
    Include { PreProc },
    Define { PreProc },
    Macro { PreProc },
    PreCondit { PreProc },

    Type { fg = hsl(P.purple), gui = "bold" },
    StorageClass { Type },
    Structure { Type },
    Typedef { Type },

    Special { fg = hsl(P.special) },
    SpecialChar { Special },
    Tag { fg = hsl(P.cyan_glow) },
    Delimiter { fg = hsl(P.delimiter) },
    SpecialComment { Comment },
    Debug { Special },

    Underlined { fg = hsl(P.cyan), gui = "underline" },
    Ignore { fg = hsl(P.bg) },
    Error { fg = hsl(P.error), bg = hsl(P.surface), gui = "bold" },
    Todo { fg = hsl(P.warn), bg = hsl(P.surface), gui = "bold,italic" },

    -- LSP semantic highlights (0.9+)
    LspReferenceText { bg = hsl(P.visual) },
    LspReferenceRead { LspReferenceText },
    LspReferenceWrite { bg = hsl(P.search) },
    LspCodeLens { fg = hsl(P.comment), gui = "italic" },
    LspCodeLensSeparator { fg = hsl(P.border) },
    LspSignatureActiveParameter { fg = hsl(P.cyan_glow), gui = "bold,underline" },

    DiagnosticError { fg = hsl(P.error) },
    DiagnosticWarn { fg = hsl(P.warn) },
    DiagnosticInfo { fg = hsl(P.info) },
    DiagnosticHint { fg = hsl(P.hint) },
    DiagnosticOk { fg = hsl(P.ok) },

    DiagnosticVirtualTextError { DiagnosticError, bg = hsl(P.surface) },
    DiagnosticVirtualTextWarn { DiagnosticWarn, bg = hsl(P.surface) },
    DiagnosticVirtualTextInfo { DiagnosticInfo, bg = hsl(P.surface) },
    DiagnosticVirtualTextHint { DiagnosticHint, bg = hsl(P.surface) },
    DiagnosticVirtualTextOk { DiagnosticOk, bg = hsl(P.surface) },

    DiagnosticUnderlineError { sp = hsl(P.error), gui = "undercurl" },
    DiagnosticUnderlineWarn { sp = hsl(P.warn), gui = "undercurl" },
    DiagnosticUnderlineInfo { sp = hsl(P.info), gui = "undercurl" },
    DiagnosticUnderlineHint { sp = hsl(P.hint), gui = "undercurl" },
    DiagnosticUnderlineOk { sp = hsl(P.ok), gui = "undercurl" },

    DiagnosticFloatingError { DiagnosticError },
    DiagnosticFloatingWarn { DiagnosticWarn },
    DiagnosticFloatingInfo { DiagnosticInfo },
    DiagnosticFloatingHint { DiagnosticHint },
    DiagnosticFloatingOk { DiagnosticOk },

    DiagnosticSignError { fg = hsl(P.error) },
    DiagnosticSignWarn { fg = hsl(P.warn) },
    DiagnosticSignInfo { fg = hsl(P.info) },
    DiagnosticSignHint { fg = hsl(P.hint) },
    DiagnosticSignOk { fg = hsl(P.ok) },

    -- Treesitter
    sym("@comment") { Comment },
    sym("@punctuation") { Delimiter },
    sym("@punctuation.bracket") { Delimiter },
    sym("@punctuation.special") { Special },

    sym("@constant") { Constant },
    sym("@constant.builtin") { Special },
    sym("@constant.macro") { Define },
    sym("@string") { String },
    sym("@string.escape") { SpecialChar },
    sym("@string.special") { SpecialChar },
    sym("@string.regexp") { Special },
    sym("@character") { Character },
    sym("@character.special") { SpecialChar },
    sym("@number") { Number },
    sym("@boolean") { Boolean },
    sym("@float") { Float },

    sym("@function") { Function },
    sym("@function.builtin") { Special },
    sym("@function.macro") { Macro },
    sym("@function.call") { Function },
    sym("@method") { Function },
    sym("@method.call") { Function },

    sym("@constructor") { Type },
    sym("@parameter") { Identifier },
    sym("@keyword") { Keyword },
    sym("@keyword.function") { Keyword },
    sym("@keyword.operator") { Operator },
    sym("@keyword.return") { Keyword },
    sym("@keyword.import") { PreProc },
    sym("@keyword.export") { PreProc },
    sym("@conditional") { Conditional },
    sym("@repeat") { Repeat },
    sym("@label") { Label },
    sym("@operator") { Operator },
    sym("@exception") { Exception },

    sym("@type") { Type },
    sym("@type.builtin") { Type },
    sym("@type.definition") { Typedef },
    sym("@type.qualifier") { Statement },
    sym("@storageclass") { StorageClass },
    sym("@attribute") { PreProc },
    sym("@field") { fg = hsl(P.fg) },
    sym("@property") { sym("@field") },

    sym("@variable") { Identifier },
    sym("@variable.builtin") { Special },
    sym("@variable.member") { sym("@field") },
    sym("@variable.parameter") { sym("@parameter") },

    sym("@namespace") { fg = hsl(P.purple_glow) },
    sym("@module") { sym("@namespace") },

    sym("@text") { Normal },
    sym("@text.literal") { String },
    sym("@text.reference") { Identifier },
    sym("@text.title") { Title },
    sym("@text.uri") { Underlined },
    sym("@text.underline") { Underlined },
    sym("@text.todo") { Todo },
    sym("@text.note") { DiagnosticInfo },
    sym("@text.warning") { DiagnosticWarn },
    sym("@text.danger") { DiagnosticError },

    sym("@markup.heading") { Title },
    sym("@markup.link") { Underlined },
    sym("@markup.link.url") { fg = hsl(P.cyan), gui = "underline" },
    sym("@markup.list") { Statement },
    sym("@markup.strong") { Normal, gui = "bold" },
    sym("@markup.italic") { Normal, gui = "italic" },
    sym("@markup.raw") { String },

    sym("@tag") { Tag },
    sym("@tag.attribute") { sym("@property") },
    sym("@tag.delimiter") { Delimiter },

    sym("@define") { Define },
    sym("@macro") { Macro },
    sym("@include") { Include },
    sym("@preproc") { PreProc },
    sym("@debug") { Debug },

    -- snacks.nvim picker (defaults link Unselected/Dir/etc. to NonText — too faint on dark neon)
    SnacksPickerNormal { bg = hsl(P.surface), fg = hsl(P.fg) },
    SnacksPickerBorder { FloatBorder },
    SnacksPickerTitle { FloatTitle },
    SnacksPickerListCursorLine { CursorLine },
    SnacksPickerCursorLine { CursorLine },
    SnacksPickerSelected { fg = hsl(P.number), gui = "bold" },
    SnacksPickerGitStatus { fg = hsl(P.fg_dim) },
    SnacksPickerUnselected { fg = hsl(P.fg_dim) },
    SnacksPickerDimmed { fg = hsl(P.comment) },
    SnacksPickerDir { fg = hsl(P.fg_dim) },
    SnacksPickerPathIgnored { fg = hsl(P.comment) },
    SnacksPickerPathHidden { fg = hsl(P.comment) },
    SnacksPickerTotals { fg = hsl(P.fg_dim) },
    SnacksPickerKeymapRhs { fg = hsl(P.fg_dim) },
    SnacksPickerBufFlags { fg = hsl(P.fg_dim) },
    SnacksPickerGitStatusIgnored { fg = hsl(P.comment) },
    SnacksPickerGitStatusUntracked { fg = hsl(P.line_nr) },
    SnacksPickerFile { fg = hsl(P.fg) },
    SnacksPickerSpecial { fg = hsl(P.magenta) },
    SnacksPickerLabel { SnacksPickerSpecial },
    SnacksPickerPrompt { bg = hsl(P.surface), fg = hsl(P.cyan) },
    SnacksPickerMatch { bg = hsl(P.surface), fg = hsl(P.pink), gui = "bold" },
    SnacksPickerInputSearch { bg = hsl(P.surface), Keyword },

    -- Neo-tree
    NeoTreeNormal { Normal },
    NeoTreeNormalNC { NormalNC },
    NeoTreeCursorLine { CursorLine },
    NeoTreeRootName { fg = hsl(P.pink), gui = "bold" },
    NeoTreeDirectoryName { fg = hsl(P.cyan) },
    NeoTreeDirectoryIcon { fg = hsl(P.cyan) },
    NeoTreeFileName { fg = hsl(P.fg) },
    NeoTreeFileIcon { fg = hsl(P.fg_dim) },
    NeoTreeSymbolicLinkTarget { fg = hsl(P.magenta), gui = "underline" },
    NeoTreeIndentMarker { fg = hsl(P.border) },
    NeoTreeExpander { fg = hsl(P.comment) },
    NeoTreeTitleBar { StatusLine },
    NeoTreeTabActive { fg = hsl(P.pink), bg = hsl(P.surface_elevated), gui = "bold" },
    NeoTreeTabInactive { fg = hsl(P.fg_dim), bg = hsl(P.surface) },
    NeoTreeTabSeparatorActive { fg = hsl(P.border), bg = hsl(P.surface_elevated) },
    NeoTreeTabSeparatorInactive { fg = hsl(P.border), bg = hsl(P.surface) },

    NeoTreeGitAdded { fg = hsl(P.ok) },
    NeoTreeGitDeleted { fg = hsl(P.error) },
    NeoTreeGitModified { fg = hsl(P.warn) },
    NeoTreeGitConflict { fg = hsl(P.magenta), gui = "bold" },
    NeoTreeGitIgnored { fg = hsl(P.comment) },
    NeoTreeGitUntracked { fg = hsl(P.hint) },
    NeoTreeGitStaged { fg = hsl(P.cyan) },

    NeoTreeFloatTitle { FloatTitle },
    NeoTreeFloatBorder { FloatBorder },
    NeoTreeMessage { fg = hsl(P.fg_dim) },
    NeoTreeDimText { fg = hsl(P.comment) },
    NeoTreeFilterTerm { fg = hsl(P.pink), gui = "bold" },
  }
end)
